import { useState, useEffect } from 'react'
import AppShell from '../../components/layout/AppShell'
import Card from '../../components/ui/Card'
import Badge from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import Spinner from '../../components/ui/Spinner'
import { Calendar, Download, RefreshCw } from 'lucide-react'
import { useSyncListener } from '../../hooks/useSync'

export default function DietPlanPage() {
  const [selectedDay, setSelectedDay] = useState('Monday')
  const [isRegenerating, setIsRegenerating] = useState(false)

  // Real-time synchronization for diet plan updates
  useSyncListener('diet_plan_update', (data) => {
    console.log('Diet plan updated remotely:', data)
    // Update local plan if administrator pushed a new one
    // In a real app, this would refresh the data from the server
  })

  useSyncListener('intervention_received', (data) => {
    if (data.type === 'DIET_RESTRICTION') {
      console.log('New diet restriction applied:', data.message)
      // Highlight the change in the UI
    }
  })

  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

  const mealPlan = {
    Monday: [
      { id: 1, name: 'Oatmeal with Berries', cuisine: 'Western', calories: 350, nutrients: ['Fiber', 'Vitamin C'] },
      { id: 2, name: 'Grilled Chicken Salad', cuisine: 'Mediterranean', calories: 450, nutrients: ['Protein', 'Iron'] },
      { id: 3, name: 'Whole Wheat Pasta', cuisine: 'Italian', calories: 520, nutrients: ['Carbs', 'Fiber'] },
      { id: 4, name: 'Greek Yogurt with Honey', cuisine: 'Greek', calories: 200, nutrients: ['Calcium', 'Protein'] },
    ],
    Tuesday: [
      { id: 5, name: 'Scrambled Eggs & Toast', cuisine: 'Western', calories: 380, nutrients: ['Protein', 'Vitamin B12'] },
      { id: 6, name: 'Vegetable Biryani', cuisine: 'Indian', calories: 480, nutrients: ['Carbs', 'Vegetables'] },
      { id: 7, name: 'Grilled Fish', cuisine: 'Asian', calories: 410, nutrients: ['Omega-3', 'Protein'] },
      { id: 8, name: 'Mixed Berries', cuisine: 'Fresh', calories: 150, nutrients: ['Vitamin C', 'Fiber'] },
    ],
  }

  const handleRegeneratePlan = () => {
    setIsRegenerating(true)
    setTimeout(() => setIsRegenerating(false), 2000)
  }

  const handleExportPlan = () => {
    // Export plan as PDF or text
    console.log('Exporting plan...')
  }

  return (
    <AppShell>
      <div className="max-w-5xl mx-auto space-y-6">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="font-display font-semibold text-3xl text-slate-900 mb-1">
              Diet Plan
            </h1>
            <p className="text-slate-600">Personalized 7-day nutrition plan generated by AI</p>
          </div>

          <div className="flex gap-2">
            <Button
              variant="secondary"
              size="sm"
              leftIcon={<Download size={16} />}
              onClick={handleExportPlan}
            >
              Export
            </Button>
            <Button
              size="sm"
              leftIcon={<RefreshCw size={16} />}
              onClick={handleRegeneratePlan}
              loading={isRegenerating}
            >
              Regenerate
            </Button>
          </div>
        </div>

        {/* Active Plan Info */}
        <Card>
          <div className="flex items-center gap-4">
            <Calendar className="text-brand-500" size={32} />
            <div className="flex-1">
              <p className="text-sm text-slate-600">Active Plan</p>
              <h2 className="font-semibold text-slate-900">7-Day Balanced Nutrition Plan</h2>
              <p className="text-xs text-slate-500 mt-1">Generated: March 27, 2026</p>
            </div>
            <Badge>
              <span>🤖</span> AI Generated
            </Badge>
          </div>
        </Card>

        {/* Preferences Summary */}
        <Card>
          <h3 className="font-semibold text-slate-900 mb-3">Plan Customizations</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              { label: 'Dietary Preference', value: 'Vegetarian' },
              { label: 'Allergies', value: 'Shellfish, Tree Nuts' },
              { label: 'Target Calories', value: '2000 kcal' },
              { label: 'Meal Frequency', value: '4 meals/day' },
            ].map((item) => (
              <div key={item.label}>
                <p className="text-xs text-slate-600 mb-1">{item.label}</p>
                <p className="font-medium text-slate-900">{item.value}</p>
              </div>
            ))}
          </div>
        </Card>

        {/* Day Tabs */}
        <div className="bg-white rounded-2xl border border-slate-100 overflow-hidden">
          <div className="grid grid-cols-7 border-b border-slate-100">
            {days.map((day) => (
              <button
                key={day}
                onClick={() => setSelectedDay(day)}
                className={`py-3 px-2 text-sm font-medium transition ${
                  selectedDay === day
                    ? 'bg-brand-50 text-brand-600 border-b-2 border-brand-600'
                    : 'text-slate-600 hover:bg-slate-50'
                }`}
              >
                {day.slice(0, 3)}
              </button>
            ))}
          </div>

          {/* Meals for Selected Day */}
          <div className="p-6 space-y-3">
            {isRegenerating ? (
              <div className="flex flex-col items-center justify-center py-12">
                <Spinner size="md" />
                <p className="text-slate-600 mt-3">Generating your personalized plan...</p>
              </div>
            ) : (
              mealPlan[selectedDay]?.map((meal) => (
                <Card key={meal.id} className="hover:shadow-elevated transition">
                  <div className="flex items-start justify-between mb-2">
                    <h3 className="font-semibold text-slate-900">{meal.name}</h3>
                    <Badge variant="info">{meal.calories} kcal</Badge>
                  </div>
                  <div className="flex items-center gap-2 mb-3">
                    <Badge variant="neutral">{meal.cuisine}</Badge>
                    <div className="flex gap-1">
                      {meal.nutrients.map((nutrient) => (
                        <span key={nutrient} className="text-xs px-2 py-1 rounded-full bg-brand-50 text-brand-700">
                          {nutrient}
                        </span>
                      ))}
                    </div>
                  </div>
                  <Button
                    variant="secondary"
                    size="sm"
                    className="w-full"
                  >
                    Mark as eaten
                  </Button>
                </Card>
              ))
            )}
          </div>
        </div>
      </div>
    </AppShell>
  )
}
